### ISSUE TITLE
NodeRED Prerequisites

### ISSUE THREAD

**Issue by Daryll-ETM** [dceejay/openwrt-node-red#7]
Hi Dceejay,

This is not an issue per say. I'm a noob seeking a little informtion. 
I use the Teltonika RUTX11 product. I am able to load the latest version of your NodeRED (v1.3.1). I believe this can run on any ARM processor, with a UI based off Lua? 
Last year, Teltonika updated thier system to run on Vue.js 2.6.12. Unfortunately, I am not able to use this code with the new changes. 
I wanted to know if it is still possible to have this node red code ported across to new implementation. I'm curious to know what is required and will everything have to be re written from scratch?

Regards,

**Comment by dceejay** [comment]
Hi, well Node-RED (latest) just needs a working nodejs 14 or better environment - ideally with access to the build tools if you want to install any extra nodes with binary components (like serialport etc). However as you have spotted I haven't updated this for a long while so this package itself is well behind the curve, and I don't have an immediate need for it so won't have time to update in the near term. But as long as nodejs can be installed and run then Node-RED should be installable on top without a problem.

**Comment by kischde** [comment]
Hi, just to let you know: I heard from Teltonika, that it is not possible to run node-red on their devices, related to hardware restrictions...
Also mentioned here: https://community.teltonika-networks.com/53032/node-red-installation?show=53032#q53032

**Comment by dceejay** [comment]
Thanks for letting me know
